INSERT INTO config_porcentajes
(concepto, porcentage, createdAt, updatedAt)
VALUES
('(ESTUCO, PANEL, PEGANTE, REJILLA, RODILLOS, PINTURA, CABLE DUPLEX, TRANSPORTE, BOTADA DE ESCOBROS,DESGASTE DE HERRAMIENTA, GASTOS DE ADM)', 34, NULL, NULL),
('DESMONTE DE ACCESORIOS, GRIFERIA, ENCINTADA DE PUERTAS, VENTANAS Y TOMAS', 1, NULL, NULL),
('1 BOTADA DE ESCOMBROS', 3, NULL, NULL),
('RELLENO', 8, NULL, NULL),
('ESTUCO', 8, NULL, NULL),
('ESTRUCTURA TAPADO DE PANEL', 3, NULL, NULL),
('MOV DE PUNTOS ELECTRICOS', 2, NULL, NULL),
('MASILLADO PANEL', 3, NULL, NULL),
('BASE PINTURA', 3, NULL, NULL),
('MORTERO Y/O MATERIAL', 4, NULL, NULL),
('ENCHAPE (PEGADA PISO)', 8, NULL, NULL),
('ENCHAPE (PEGADA DE BAÑOS)', 6, NULL, NULL),
('ENCHAPE (ZONA DE OFICIOS)', 2, NULL, NULL),
('FRAGUA', 1, NULL, NULL),
('INSTALACION DE ILUMINACION (TOMAS INTERUPTORES)', 1, NULL, NULL),
('INSTALACION DE BAÑOS', 1, NULL, NULL),
('INSTALACION DE ACCESORIOS', 1, NULL, NULL),
('TERMINACION DE DETALLES (ACABADOS)', 4, NULL, NULL),
('2 ASEO', 2, NULL, NULL),
('CUANDO EL CLIENTE RECIBA', 5, NULL, NULL);